<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<?php echo $this->headMeta()->appendName('description', $this->escape(Model_Settings::findActiveParam('meta_description')))
                            ->appendName('keywords', $this->escape(Model_Settings::findActiveParam('keywords')) . $this->categoriesList()); ?>

<?php echo $this->headTitle()."\n"; ?>
<?php echo $this->headLink(array('rel' => 'shortcut icon', 'href' => '/favicon.ico'))
                            ->appendStylesheet($this->baseUrl().'/css/reset.css')
                            //->appendStylesheet($this->baseUrl().'/css/text.css')
                            ->appendStylesheet($this->baseUrl().'/css/960.css')
                            ->appendStylesheet($this->baseUrl().'/css/site.css');
       //echo $this->headScript()->appendFile('/ckeditor/ckeditor.js', $type = 'text/javascript');
       echo $this->headScript()->prependFile($this->baseUrl() . '/scripts/shadow.js', $type = 'text/javascript')
                               ->prependFile($this->baseUrl() . '/scripts/global.js', $type = 'text/javascript')
                               ->prependFile('http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js', $type = 'text/javascript');?>
<link rel="alternate" type="application/rss+xml" title="Blog RSS" href="/blogs/rss" />
<?php if(Model_Settings::findActiveParam('site_css') != ""): ?>
<style type="text/css">
<?php echo $this->escape(Model_Settings::findActiveParam('site_css'));?>
</style>
<?php endif; ?>
<?php if ('production' == APPLICATION_ENV): ?>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-4205070-20']);
  _gaq.push(['_setDomainName', '.smotko.si']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<?php endif ?>
<link href='http://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css' />
</head>
<body>
  <div class="wrapper">
  <div class="header_bg">
<div class="container_12" id="header">
<!---
<div title="Vesele praznike" style="z-index:666;position:absolute;top: 0px;  left: 351px;background-image:url(/images/santa.gif);width:87px;height:87px;margin-left: 220px;"></div>
-->
    <div class="grid_4">
        <h1 class="site_title"><a href="/"><?php echo $this->escape(Model_Settings::findActiveParam('site_title'));?></a></h1>
        <p class="site_description"><?php echo $this->escape(Model_Settings::findActiveParam('site_description'));?></p>
    </div>
    <div class="grid_8" id="menu">
        <span id="login-info" class="textshadow">

        </span>

          <?php echo $this->navigation()->menu()->renderMenu(null, array('maxDepth' => 0)); ?>

       

        
    </div>
  </div>
</div>
<div class="container_12" id="content">
<?php echo $this->statusMessage(); ?>
<?php echo $this->layout()->content; ?>
</div>
    <div class="push"></div>
</div>

  <div  id="footer" class="footer">
<div class="container_12">
            <p class="textshadow grid_12">Powered by <a href="https://github.com/Smotko/smotko" title="Če te izvedba strani moti, lahko popraviš sam!">smotko blog</a></p>
    </div>
  </div> 
</body>
</html>
