<div class="grid_12">
  <div class="grid_9 boxshadow alpha main">
      <div id = "new_debate">Nova sporočila!</div>
      <div class="debate_content">
    <?php $this->debate->index = true; echo $this->partialLoop('comments/comment.phtml', $this->debate); ?>

    <?php
echo $this->paginationControl($this->debate, 'Sliding', 'pagination.phtml');
?>
      </div>

    <?php echo $this->debateForm; ?>

    </div>
  <div class="grid_3 omega">
    <div class="pnp">

    <?php if($this->isAdmin() && $this->unconfirmedPnps > 0): ?>
    <p class="notice">Št. nepotrjenih <a href="/admin/pnp">PNP</a>jev je <?php echo $this->unconfirmedPnps;?>!</p>
    <?php endif ?>
    <?php if($this->pnp):?>
    <p class="meta">
    <?php echo $this->dateFormat($this->pnp['date']);?>
    </p>
    <div title="<?php echo $this->dateFormat($this->pnp['date']);?>">
    
    <p class="pnp_content">
        <?php echo $this->prepareContent($this->pnp['content'], $this->pnp['markdown']); ?>
    </p>
    <p class="author">
        Napisal/a: <?php echo $this->escape($this->pnp['User']['user_name']);?>
    </p>

    </div>

    <?php endif; ?>
    <p><a href="/pnp" id="add-pnp">Dodaj PNP</a></p>
    <div id="pnp-form"><?php echo $this->pnp_form?></div>
    </div>
<!--    <div class="boxshadow grad">
    <h1>Zadnji komentarji</h1>
    <?php echo $this->partialLoop('comments/commentLink.phtml', $this->comments); ?>
    </div>

    <div class="boxshadow grad">
    <h1>Zadnji blogi:</h1>
    <?php echo $this->partialLoop('blog/blog-title.phtml', $this->blogs); ?>
</div>
-->
    <div class="boxshadow grad">
    <?php if($this->userId()): ;?>

    <p><a href="/user/logout/" title="Uporabno, če stran uporabljate na javnem računalniku.">Odjavi se</a></p>
    </div>
    <?php else: ?>


    <?php echo $this->user; ?>

    </div>
    <?php endif; ?>
<!--
<div class="boxshadow grad">

    <ol class="zgovorni">
    <?php foreach($this->users as $usr): ?>
    <li><a href="#" title="Št. prispevkov: <?php echo $usr['debateCount'];?>"><?php echo $usr['user_name'];?></a></li>
    <?php endforeach; ?>
    </ol>
</div>
-->
  </div>
</div>

