<div class="grid_12">
  <div class="grid_3 alpha">
    <div class="boxshadow">
  <h1>Današnji PNP:</h1>
    <?php if($this->isAdmin() && $this->unconfirmedPnps > 0): ?>
    <p class="notice">Št. nepotrjenih <a href="/admin/pnp">PNP</a>jev je <?php echo $this->unconfirmedPnps;?>!</p>
    <?php endif ?>
    <?php if($this->pnp):?>
    <div class="chat">
    <p class="meta">
        <?php echo $this->dateFormat($this->pnp['date']);?>
    </p>
    <p class="pnp_content">
        <?php echo $this->pnp['content']; ?>
    </p>
    <p class="author">
        Napisal/a: <?php echo $this->pnp['User']['user_name'];?>
    </p>

    </div>
    <?php endif; ?>
    <p><a href="/pnp">Dodaj svoj PNP</a></p>
    </div>
    <div class="boxshadow">
    <h1>Zadnji komentarji</h1>
    <?php echo $this->partialLoop('comments/commentLink.phtml', $this->comments); ?>
    </div>
    
    <div class="boxshadow">
    <h1>Login n' stuff</h1>
    <?php echo $this->user; ?>
    </div>

    <div class="boxshadow">
    <h1>Zadnji blogi:</h1>
    <?php echo $this->partialLoop('blog/blog-title.phtml', $this->blogs); ?>
</div>

    <div class="boxshadow">
    <?php if($this->userId()): ;?>
    <h1>Odjava</h1>
    <p><a href="/index/logout/" title="Uporabno, če stran uporabljate na javnem računalniku.">Odjavi se</a></p>
    </div>
    <?php endif; ?>
  </div>
  <div class="grid_9 boxshadow omega">
      <h1>Debate:</h1>
      <div id = "new_debate">Nova sporočila!</div>
      <div class="debate_content">
    <?php $this->debate->index = true; echo $this->partialLoop('comments/comment.phtml', $this->debate); ?>

    <?php echo $this->paginationControl($this->debate,
                                    'Sliding',
                                    'pagination.phtml'); ?>
      </div>
    <h2>Prispevaj:</h2>
    <?php echo $this->debateForm; ?>

    </div>
</div>

