<?php

/**
 * Model_Base_Categories
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Post
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_Categories extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('categories');
        $this->hasColumn('name', 'string', 25, array(
             'type' => 'string',
             'length' => '25',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Model_Post as Post', array(
             'refClass' => 'Model_PostCategories',
             'local' => 'categorie_id',
             'foreign' => 'post_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'name',
             ),
             'canUpdate' => true,
             ));
        $this->actAs($sluggable0);
    }
}