<?php

/**
 * Model_Base_Post
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $title
 * @property string $excerpt
 * @property string $content
 * @property string $style
 * @property string $status
 * @property string $type
 * @property integer $commentCount
 * @property Model_User $User
 * @property Doctrine_Collection $Comments
 * @property Doctrine_Collection $Categories
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_Post extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('post');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('excerpt', 'string', 1000, array(
             'type' => 'string',
             'length' => '1000',
             ));
        $this->hasColumn('content', 'string', 10000, array(
             'type' => 'string',
             'length' => '10000',
             ));
        $this->hasColumn('style', 'string', 1000, array(
             'type' => 'string',
             'length' => '1000',
             ));
        $this->hasColumn('status', 'string', 25, array(
             'type' => 'string',
             'length' => '25',
             ));
        $this->hasColumn('type', 'string', 25, array(
             'type' => 'string',
             'length' => '25',
             ));
        $this->hasColumn('commentCount', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_User as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasMany('Model_Comments as Comments', array(
             'local' => 'id',
             'foreign' => 'post_id'));

        $this->hasMany('Model_Categories as Categories', array(
             'refClass' => 'Model_PostCategories',
             'local' => 'post_id',
             'foreign' => 'categorie_id'));

        $versionable0 = new Doctrine_Template_Versionable(array(
             'versionColumn' => 'version',
             'className' => '%CLASS%Version',
             'auditLog' => true,
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'title',
             ),
             'canUpdate' => true,
             ));
        $this->actAs($versionable0);
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}