<?php

/**
 * Model_Base_SettingsMeta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $settings_id
 * @property string $metaKey
 * @property string $metaValue
 * @property Model_Settings $Settings
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_SettingsMeta extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('settings_meta');
        $this->hasColumn('settings_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('metaKey', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('metaValue', 'string', 1000, array(
             'type' => 'string',
             'length' => '1000',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_Settings as Settings', array(
             'local' => 'settings_id',
             'foreign' => 'id'));
    }
}