<div class="grid_9 boxshadow">
    
    <?php $i = 0; $first = true; $last = false; foreach($this->pnp as $pnp):?>
    <?php if($i % 3 == 0) $first = true; else $first = false;
           if($i % 3 == 2) $last = true; else $last = false;
           $i++;
    ?>
    <div class="pnp chat grid_3<?php if($first) echo ' alpha'; else if($last) echo ' omega'?>">
    <p class="meta">
        <?php echo $this->dateFormat($pnp['date']);?>
    </p>
    <p class="pnp_content">
        <?php echo $this->prepareContent($pnp['content'], $pnp['markdown']);?>
    </p>
    <p class="author">
       Napisal/a: <?php echo $this->escape($pnp['User']['user_name']); ?>
    </p>
    </div>
    <?php if($last):?>
    <div class="clear"></div>
    <?php endif; ?>
    <?php endforeach; ?>
    <?php echo $this->paginationControl($this->pnp,
                                    'Sliding',
                                    'pagination.phtml'); ?>
</div>
<div class="grid_3">
    <?php echo $this->form;?>
</div>