<?php

/**
 * Model_Comments
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_Comments extends Model_Base_Comments
{
    
    public static function getComments()
    {
        return Doctrine_Query::create()
                ->select()
                ->from('Model_Comments c')
                ->leftJoin('c.User u, c.Post p')
                ->orderBy('created_at DESC')
                ->fetchArray();
        
    }
    public static function getCommentById($id)
    {
        return Doctrine_Query::create()
                ->select()
                ->from('Model_Comments c')
                ->leftJoin('c.User u, c.Post p')
                ->where('c.id = ?', $id)
                ->fetchOne();

    }
    public function setUserUrl($url)
    {

        return $this->_set('user_url', 'http://' . str_replace('http://', '', $url));
    }
    public function deleteComment($id)
    {
        $user = Zend_Registry::get('User');

        $comment = Doctrine_Core::getTable('Model_Comments')->findOneById($id);
        if($comment->user_id != $user['id'] && $user['role'] != 'admin')
            throw new Exception('Ne smeš brisat komentarjev drugih!');
        $comment->Post->commentCount -= 1;
        $comment->User->commentCount -= 1;
        $comment->User->save();
        $comment->Post->save();
        $comment->delete();
        


    }
    public function deleteDebate($id)
    {
        $user = Zend_Registry::get('User');
        $debate = Doctrine_Core::getTable('Model_Debate')->findOneById($id);
        if($debate->User->id != $user['id'] && $user['role'] != 'admin')
            throw new Exception('Ne smeš brisat komentarjev drugih!');
        $debate->User->debateCount--;
        $debate->User->save();
        $debate->delete();
    }

}