<?php

/**
 * Model_Debate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_Debate extends Model_Base_Debate
{
    public static function getDebate()
    {
        return Doctrine_Query::create()
                ->select()
                ->from('Model_Debate c')
                ->leftJoin('c.User u')
                ->orderBy('created_at DESC')
                ->fetchArray();
    }
    public static function getDebateById($id)
    {
        return Doctrine_Query::create()
                ->select()
                ->from('Model_Debate d')
                ->leftJoin('d.User u')
                ->where('d.id = ?', $id)
                ->fetchOne();

    }
    public static function getDebateByUser($id)
    {
        return Doctrine_Query::create()
                ->select()
                ->from('Model_Debate c')
                ->leftJoin('c.User u')
                ->where('user_id = ?', $id)
                ->orderBy('created_at DESC')
                ->fetchArray();
    }
    public static function getHighest()
    {
        return Doctrine_Query::create()
                ->select('id')
                ->from('Model_Debate d')
                ->orderBy('id DESC')
                ->fetchOne();
        
    }
    public function setUserUrl($url)
    {
        
        return $this->_set('user_url', 'http://' . str_replace('http://', '', $url));
    }
}