<?php

/**
 * Model_Post
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_Post extends Model_Base_Post
{

    public static function findById($id){
    	
        return Doctrine_Query::create()
                    ->select()
                    ->from('Model_Post p')
                    ->leftJoin('p.Categories c, p.User u')
                    ->where('p.id = ?', $id)
                    ->fetchOne();
        
    }
    public static function findBySlug($slug){
        return Doctrine_Query::create()
                    ->select()
                    ->from('Model_Post p')
                    ->leftJoin('p.Categories c, p.User u, p.Comments co')
                    ->leftJoin('co.User cu')
                    ->where('p.slug = ?', $slug)
                    ->fetchArray();
    }
    public static function getLatestBlogs()
    {
        return Doctrine_Query::create()
                    ->select()
                    ->from('Model_Post p')
                    ->leftJoin('p.Categories c')
                    ->leftJoin('p.User u')
                    ->where('type = ?', 'blog')
                    ->limit('5')
                    ->orderBy('created_at DESC')
                    ->fetchArray();
    }
    public static function getBlogsByCategories($catSlug)
    {
        $ids = Doctrine_Query::create()
                    ->select('c.id, p.id')
                    ->from('Model_Categories c')                    
                    ->leftJoin('c.Post p')
                    ->where('p.type = ?', 'blog')
                    ->andWhere('c.slug = ?', $catSlug)
                    ->fetchArray();
        
        return Doctrine_Query::create()
                    ->select()
                    ->from('Model_Post p')
                    ->leftJoin('p.Categories c')
                    ->leftJoin('p.User u')
                    ->where('type = ?', 'blog')
                    ->andWhereIn($ids)
                    ->orderBy('created_at DESC')
                    ->fetchArray();
        
    }

    public function getFeed(){

        $arr = Doctrine_Query::create()
                    ->select()
                    ->from('Model_Post p')
                    ->leftJoin('p.Categories c')
                    ->leftJoin('p.User u')
                    ->where('type = ?', 'blog')
                    ->limit('20')
                    ->orderBy('created_at DESC')
                    ->fetchArray();

        $i = 0;
        $entries = array();
        foreach ($arr AS $blog) {
            if(!isset($published)){
                $published = (int)strtotime($blog['created_at']);
            }
            //TODO: Set permalink & link should not be /stran/.
            $entry = array(
                'guid'          => $blog['id'],
                'title'       => $blog['title'],
                'link'        => 'http://smotko.si/blog/' . $blog['slug'],
                'lastUpdate' => (int)strtotime($blog['updated_at']),
                'description' => $blog['content'],
                'author'     => $blog['User']['user_name'],
            );
            array_push($entries, $entry);
        }

        // Create the RSS array
        return array(
            'title'   => 'Smotko.si - blog',
            'link'    => 'http://smotko.si/blog',
            'charset' => 'utf-8',
            'published' => $published,
            'entries' => $entries
        );
    }
}