<?php

/**
 * Model_Settings
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_Settings extends Model_Base_Settings
{

    private static $_active;


    public static function findActive($id = 0)
    {
    	
        $q = Doctrine_Query::create()->select()
                                         ->from('Model_Settings s')
                                         ->leftJoin('s.SettingsMeta m');
        if($id == 0)
            $q->where('active = ?', true);
        else
            $q->where('id = ?', $id);
        $arr = $q->fetchArray();
        return $arr[0];
    }
    public static function setPrimary($id)
    {
        $q = Doctrine_Query::create()
                ->update('Model_Settings')
                ->set('active', 0)
                ->execute();

        $q = Doctrine_Query::create()
                ->update('Model_Settings')
                ->set('active', 1)
                ->where('id = ?', $id)
                ->execute();
    }
    public static function findActiveParam($param)
    {
        //TODO: there is much room for optimization:
        $q = Doctrine_Query::create()
            ->select('m.metaValue')
            ->from('Model_SettingsMeta m')
            ->leftJoin('m.Settings s')
            ->where('s.active = 1')
            ->andWhere('m.metaKey = ?', $param)
            ->limit(1)
            ->fetchArray();
     return isset ($q[0]) ? $q[0]['metaValue'] : "";
    }
    public static function deleteId($id)
    {
        //TODO: this can be done faster:
        $settings = Doctrine_Core::getTable('Model_Settings')->findOneBy('id', $id);
        if($settings->active == 1){
            $settings->delete();
            //Make the first setting active:
            $q = Doctrine_Query::create()
                    ->update('Model_Settings')
                    ->set('active', 1)
                    ->limit(1)
                    ->orderBy('id ASC')
                    ->execute();
        }
        $settings->delete();
    }
}