<p class="alignLeft">
<?php if($this->User['user_url'] != null && $this->User['user_url'] != 'http://')
        echo '<a href="' . $this->escape($this->User['user_url']) . '" title="'.$this->escape($this->User['user_url']).'">' . $this->escape($this->user_name) . '</a>';
    else
        echo '<span class="user" title="Napisano: '. $this->dateTimeFormat($this->created_at) .'">' . $this->escape($this->user_name) . '</span>'; ?> je komentiral/a
    <a href="/blog/<?php echo $this->Post['slug'];?>"><?php echo $this->Post['title']; ?></a></p>